name: gis-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - jupyterlab
  - ipykernel
  - rasterio
  - rasterstats
  - folium
  - mapclassify